// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${env("MYSQL_DATABASE_USER")}:${env("MYSQL_DATABASE_PASSWORD")}@${env("MYSQL_DATABASE_HOST")}:${env("MYSQL_DATABASE_PORT")}/${env("MYSQL_DATABASE_NAME")}?sslaccept=strict`,
    // shadowDatabaseUrl: env("SHADOW_DATABASE_URL"),
  },
});
